<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Floowan.Core</RootNamespace>
    <AssemblyName>Floowan.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssetsTools.NET" Version="3.0.4" />
    <PackageReference Include="AssetsTools.NET.Texture" Version="3.0.2" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.11" />
    <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.20.1" />
    <PackageReference Include="Microsoft.Win32.Registry" Version="5.0.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

    <ItemGroup>
    <None Include="Resources\classdata.tpk">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>classdata.tpk</Link>
    </None>
    <None Include="Resources\frames\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>frames\%(Filename)%(Extension)</Link>
    </None>
    <EmbeddedResource Include="Resources\cutin\monster_cutin.csv" />
    <None Include="Resources\cutin\monster_cutin.csv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Link>Resources\cutin\monster_cutin.csv</Link>
    </None>
  </ItemGroup>

</Project>
