<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon />
    <RootNamespace>Floowan.Desktop</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Floowan.Core\Floowan.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\Floowan.Core\Resources\classdata.tpk" Link="classdata.tpk" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\database.db" Link="database.db" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
