using System.Diagnostics;
using System.IO;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using Floowan.Core.Assets;
using Floowan.Core.Data;
using Floowan.Core.Game;
using Floowan.Core.Imaging;
using Floowan.Core.Models;
using Floowan.Core.Services;
using Microsoft.Win32;

namespace Floowan.Desktop;

public partial class MainWindow : Window
{
    private const int DbPageSize = 100;
    private const int AutoSearchMinLength = 3;
    private const int SearchDebounceMs = 250;

    private CardDatabase? _database;
    private CardArtModService? _modService;
    private OverFrameModService? _overFrameService;
    private AutoOverFrameArtService? _autoOverFrameArtService;
    private CardRecord? _selected;
    private CardRecord? _ofSelected;
    private string? _replacementImagePath;
    private string? _ofReplacementImagePath;
    private string? _previewTempPath;
    private string? _ofPreviewTempPath;
    private string? _ofAutoGeneratedTempPath;
    private bool _ofGateReady;
    private bool _ofInitialScanStarted;
    /// <summary>True when live texture is already over-frame sized (DB flag and/or 704?1024).</summary>
    private bool _ofLiveTextureIsOverframe;

    private CardRecord? _dbSelected;
    private int _dbOffset;
    private int _dbTotalMatching;

    private string _backupRoot = Path.Combine(AppContext.BaseDirectory, "backups");

    private readonly DispatcherTimer _cardSearchDebounceTimer;
    private readonly DispatcherTimer _ofSearchDebounceTimer;
    private readonly CardThumbnailCache _thumbnailCache = new();

    /// <summary>Session-scoped results view: list vs thumbnails (shared by Card Art and Over-frame).</summary>
    private bool _useThumbnailView;
    private bool _viewModeUpdating;
    private int _thumbnailLoadGeneration;
    private int _uiBusyDepth;
    public MainWindow()
    {
        InitializeComponent();
        _cardSearchDebounceTimer = CreateSearchDebounceTimer(OnCardSearchDebounceTick);
        _ofSearchDebounceTimer = CreateSearchDebounceTimer(OnOfSearchDebounceTick);
        Loaded += OnLoaded;
        Closed += (_, _) => Cleanup();
    }

    /// <summary>
    /// Blocks interaction with a dim overlay. Avoids Window.IsEnabled=false, which
    /// forces ListBox/ListBoxItem into the default disabled (white) chrome.
    /// </summary>
    private void SetUiBusy(bool busy)
    {
        if (busy)
        {
            if (_uiBusyDepth++ == 0)
            {
                MainContent.IsHitTestVisible = false;
                BusyOverlay.Visibility = Visibility.Visible;
                Cursor = Cursors.Wait;
            }
            return;
        }

        if (_uiBusyDepth == 0)
            return;
        if (--_uiBusyDepth != 0)
            return;

        MainContent.IsHitTestVisible = true;
        BusyOverlay.Visibility = Visibility.Collapsed;
        ClearValue(CursorProperty);
    }
    private static DispatcherTimer CreateSearchDebounceTimer(EventHandler tick)
    {
        var timer = new DispatcherTimer { Interval = TimeSpan.FromMilliseconds(SearchDebounceMs) };
        timer.Tick += tick;
        return timer;
    }

    private void OnLoaded(object sender, RoutedEventArgs e)
    {
        try
        {
            _backupRoot = Path.Combine(AppContext.BaseDirectory, "backups");
            ToolsBackupPathBox.Text = _backupRoot;
            _modService = new CardArtModService(backupRoot: _backupRoot);
            _overFrameService = new OverFrameModService(backupRoot: _backupRoot);
            _autoOverFrameArtService = new AutoOverFrameArtService();

            var defaultDb = FindDefaultDatabase();
            if (defaultDb is not null)
                OpenDatabase(defaultDb);

            var discovered = GamePathLocator.FindSteamMasterDuelPaths();
            if (discovered.Count == 1)
            {
                SetGamePath(discovered[0]);
            }
            else if (_database?.GetStoredGamePath() is string stored &&
                     GamePathLocator.IsValidGamePath(stored, out _))
            {
                SetGamePath(stored);
            }

            Status($"Loaded. Cards in DB: {_database?.CountCards() ?? 0}. Discovered installs: {discovered.Count}.");
            ApplyResultsViewMode(_useThumbnailView);
            if (_database is not null)
            {
                RunSearch();
                RunOfSearch();
                RefreshOfGateStatusFromCache();
                RunDatabaseQuery(resetOffset: true);
            }
        }
        catch (Exception ex)
        {
            Status("Startup error: " + ex.Message);
            MessageBox.Show(ex.Message, "Floowan", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    private static string? FindDefaultDatabase()
    {
        var candidates = new[]
        {
            Path.Combine(AppContext.BaseDirectory, "database.db"),
            Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", "..", "database.db")),
            Path.Combine(Directory.GetCurrentDirectory(), "database.db"),
            @"C:\Users\user\Documents\Projects\Floowan-copy\database.db"
        };
        return candidates.FirstOrDefault(File.Exists);
    }

    private void OpenDatabase(string path)
    {
        _database?.Dispose();
        var userPath = UserDatabasePaths.ResolveDefaultPath();
        _database = new CardDatabase(path, userPath);
        DatabasePathBox.Text = path;
        UserDatabasePathBox.Text = _database.UserDatabasePath;
        var flag = _database.GetCreateBackupFlag();
        if (flag is bool b)
            CreateBackupBox.IsChecked = b;

        RefreshOfGateStatusFromCache();
    }

    private void SetGamePath(string path)
    {
        GamePathBox.Text = path;
        try { _database?.SetStoredGamePath(path); } catch { /* read-only ok */ }
        _ofGateReady = false;
        RefreshOfGateStatusFromCache();
    }

    private void DiscoverSteam_Click(object sender, RoutedEventArgs e)
    {
        var paths = GamePathLocator.FindSteamMasterDuelPaths();
        if (paths.Count == 0)
        {
            MessageBox.Show("No valid Master Duel LocalData folders were found via Steam libraries.", "Floowan");
            return;
        }

        if (paths.Count == 1)
        {
            SetGamePath(paths[0]);
            Status("Selected LocalData: " + paths[0]);
            return;
        }

        var choice = paths[0];
        var dlg = new Window
        {
            Title = "Select Master Duel player data",
            Owner = this,
            Width = 720,
            Height = 360,
            WindowStartupLocation = WindowStartupLocation.CenterOwner,
            Background = Background,
            Foreground = Foreground
        };
        var list = new ListBox { Margin = new Thickness(12) };
        foreach (var p in paths)
            list.Items.Add(p);
        list.SelectedIndex = 0;
        var ok = new Button { Content = "OK", Width = 80, Margin = new Thickness(12), IsDefault = true };
        ok.Click += (_, _) => { choice = (string)list.SelectedItem; dlg.DialogResult = true; };
        var panel = new DockPanel();
        DockPanel.SetDock(ok, Dock.Bottom);
        panel.Children.Add(ok);
        panel.Children.Add(list);
        dlg.Content = panel;
        if (dlg.ShowDialog() == true)
        {
            SetGamePath(choice);
            Status("Selected LocalData: " + choice);
        }
    }

    private void BrowseGamePath_Click(object sender, RoutedEventArgs e)
    {
        var dlg = new OpenFolderDialog { Title = "Select Master Duel LocalData/<playerId> folder" };
        if (dlg.ShowDialog(this) == true)
        {
            if (!GamePathLocator.IsValidGamePath(dlg.FolderName, out var error))
            {
                MessageBox.Show(error ?? "Invalid path", "Floowan", MessageBoxButton.OK, MessageBoxImage.Warning);
                return;
            }
            SetGamePath(dlg.FolderName);
            Status("Selected LocalData: " + dlg.FolderName);
        }
    }

    private void BrowseDatabase_Click(object sender, RoutedEventArgs e)
    {
        var dlg = new OpenFileDialog
        {
            Title = "Open master card catalog (database.db)",
            Filter = "SQLite DB (*.db)|*.db|All files|*.*"
        };
        if (dlg.ShowDialog(this) == true)
        {
            OpenDatabase(dlg.FileName);
            RunSearch();
            RunOfSearch();
            RunDatabaseQuery(resetOffset: true);
            Status(
                "Opened master: " + dlg.FileName +
                " Â· user: " + (_database?.UserDatabasePath ?? UserDatabasePaths.ResolveDefaultPath()));
        }
    }

    private void SearchBox_KeyDown(object sender, KeyEventArgs e)
    {
        if (e.Key == Key.Enter)
        {
            _cardSearchDebounceTimer.Stop();
            RunSearch();
        }
    }

    private void SearchBox_TextChanged(object sender, TextChangedEventArgs e)
    {
        _cardSearchDebounceTimer.Stop();
        _cardSearchDebounceTimer.Start();
    }

    private void OnCardSearchDebounceTick(object? sender, EventArgs e)
    {
        _cardSearchDebounceTimer.Stop();
        ApplyDebouncedTextSearch(
            SearchBox.Text,
            RunSearch,
            () =>
            {
                CardList.ItemsSource = Array.Empty<CardRecord>();
                Status("Type at least 3 characters to search.");
            });
    }

    private void Search_Click(object sender, RoutedEventArgs e)
    {
        _cardSearchDebounceTimer.Stop();
        RunSearch();
    }

    private void RunSearch()
    {
        if (_database is null)
        {
            Status("Open database.db first.");
            return;
        }

        var results = _database.SearchCards(
            SearchBox.Text,
            favoritesOnly: FavoritesOnlyBox.IsChecked == true,
            searchDescription: SearchDescBox.IsChecked == true,
            limit: 400);
        CardList.ItemsSource = results;
        BumpThumbnailLoadGeneration();
        Status($"Showing {results.Count} card(s).");
    }

    private void CardResultsViewMode_Changed(object sender, RoutedEventArgs e)
    {
        if (_viewModeUpdating || CardArtViewThumbRadio is null)
            return;
        ApplyResultsViewMode(CardArtViewThumbRadio.IsChecked == true);
    }

    private void OfResultsViewMode_Changed(object sender, RoutedEventArgs e)
    {
        if (_viewModeUpdating || OfViewThumbRadio is null)
            return;
        ApplyResultsViewMode(OfViewThumbRadio.IsChecked == true);
    }

    private void ApplyResultsViewMode(bool thumbnails)
    {
        if (CardList is null || OfCardList is null)
            return;

        _viewModeUpdating = true;
        try
        {
            _useThumbnailView = thumbnails;
            if (CardArtViewListRadio is not null)
                CardArtViewListRadio.IsChecked = !thumbnails;
            if (CardArtViewThumbRadio is not null)
                CardArtViewThumbRadio.IsChecked = thumbnails;
            if (OfViewListRadio is not null)
                OfViewListRadio.IsChecked = !thumbnails;
            if (OfViewThumbRadio is not null)
                OfViewThumbRadio.IsChecked = thumbnails;

            ApplyListBoxViewMode(CardList, thumbnails, useDisplayMemberPath: true, listItemTemplate: null);
            ApplyListBoxViewMode(
                OfCardList,
                thumbnails,
                useDisplayMemberPath: false,
                listItemTemplate: TryFindResource("OfCardListItemTemplate") as DataTemplate);
            BumpThumbnailLoadGeneration();
        }
        finally
        {
            _viewModeUpdating = false;
        }
    }

    private void ApplyListBoxViewMode(
        ListBox list,
        bool thumbnails,
        bool useDisplayMemberPath,
        DataTemplate? listItemTemplate)
    {
        if (thumbnails)
        {
            list.DisplayMemberPath = null;
            list.ItemTemplate = TryFindResource("CardThumbnailItemTemplate") as DataTemplate;
            list.ItemsPanel = (ItemsPanelTemplate)FindResource("CardThumbnailItemsPanel");
        }
        else
        {
            list.ItemTemplate = listItemTemplate;
            list.DisplayMemberPath = useDisplayMemberPath ? "DisplayName" : null;
            list.ItemsPanel = (ItemsPanelTemplate)FindResource("CardListItemsPanel");
        }
    }

    private void BumpThumbnailLoadGeneration() => Interlocked.Increment(ref _thumbnailLoadGeneration);

    private async void CardThumbnailImage_Loaded(object sender, RoutedEventArgs e)
    {
        if (!_useThumbnailView)
            return;
        if (sender is not Image image || image.DataContext is not CardRecord card)
            return;

        var generation = _thumbnailLoadGeneration;
        if (_thumbnailCache.TryGet(card, out var cached) && !ReferenceEquals(cached, _thumbnailCache.Placeholder))
        {
            image.Source = cached;
            return;
        }

        image.Source = _thumbnailCache.Placeholder;

        try
        {
            var loaded = await _thumbnailCache.GetOrLoadAsync(GamePathBox.Text, card);
            if (generation != _thumbnailLoadGeneration)
                return;
            if (!image.IsLoaded || image.DataContext is not CardRecord current || current.Id != card.Id)
                return;
            image.Source = loaded;
        }
        catch (OperationCanceledException)
        {
            /* ignore */
        }
        catch
        {
            if (image.IsLoaded)
                image.Source = _thumbnailCache.Placeholder;
        }
    }

    private void CardList_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        _selected = CardList.SelectedItem as CardRecord;
        _replacementImagePath = null;
        ReplacementImage.Source = null;
        ImagePathText.Text = "";
        DetailText.Text = "";

        if (_selected is null)
        {
            CardTitleText.Text = "(none selected)";
            CardMetaText.Text = "";
            CurrentArtImage.Source = null;
            return;
        }

        CardTitleText.Text = _selected.DisplayName;
        CardMetaText.Text = $"Bundle {_selected.Bundle} ? id {_selected.Id} ? backup={_selected.HasBackup}";
        LoadCurrentPreview();
    }

    private void LoadCurrentPreview()
    {
        if (_selected is null || _modService is null || string.IsNullOrWhiteSpace(GamePathBox.Text))
            return;

        try
        {
            CleanupPreviewTemp();
            _previewTempPath = Path.Combine(Path.GetTempPath(), $"floowan-preview-{Guid.NewGuid():N}.png");
            _modService.ExtractCardArt(GamePathBox.Text, _selected, _previewTempPath);
            CurrentArtImage.Source = LoadBitmap(_previewTempPath);
            var info = _modService.GetTextureInfo(GamePathBox.Text, _selected);
            DetailText.Text = $"Texture '{info.Name}' {info.Width}x{info.Height} format={info.Format} mips={info.MipCount}";
        }
        catch (Exception ex)
        {
            CurrentArtImage.Source = null;
            DetailText.Text = "Preview failed: " + ex.Message;
        }
    }

    private void SelectImage_Click(object sender, RoutedEventArgs e)
    {
        var dlg = new OpenFileDialog
        {
            Title = "Select replacement card art",
            Filter = "Images|*.png;*.jpg;*.jpeg;*.bmp;*.webp|All files|*.*"
        };
        if (dlg.ShowDialog(this) != true)
            return;

        _replacementImagePath = dlg.FileName;
        ImagePathText.Text = "Replacement: " + dlg.FileName;
        ReplacementImage.Source = LoadBitmap(dlg.FileName);
        ReplacementImage.Opacity = 1.0;
        CurrentArtImage.Opacity = 0.35;
    }

    private async void Replace_Click(object sender, RoutedEventArgs e)
    {
        if (_modService is null || _selected is null)
        {
            MessageBox.Show("Select a card first.", "Floowan");
            return;
        }
        if (string.IsNullOrWhiteSpace(GamePathBox.Text))
        {
            MessageBox.Show("Set the Master Duel LocalData path first.", "Floowan");
            return;
        }
        if (string.IsNullOrWhiteSpace(_replacementImagePath))
        {
            MessageBox.Show("Select a replacement image first.", "Floowan");
            return;
        }

        var createBackup = CreateBackupBox.IsChecked == true;
        var gamePath = GamePathBox.Text;
        var card = _selected;
        var image = _replacementImagePath;
        SetUiBusy(true);
        Status("Replacing card art…");
        try
        {
            var result = await Task.Run(() =>
                _modService.ReplaceCardArt(gamePath, card, image, createBackup, _database));
            Status(result.Message);
            MessageBox.Show(result.Message, "Floowan",
                MessageBoxButton.OK,
                result.Success ? MessageBoxImage.Information : MessageBoxImage.Error);
            if (result.Success)
            {
                CurrentArtImage.Opacity = 1.0;
                ReplacementImage.Opacity = 0.0;
                _thumbnailCache.Invalidate(card);
                LoadCurrentPreview();
            }
        }
        finally
        {
            SetUiBusy(false);
        }
    }

    private void Extract_Click(object sender, RoutedEventArgs e)
    {
        if (_modService is null || _selected is null || string.IsNullOrWhiteSpace(GamePathBox.Text))
            return;

        var dlg = new SaveFileDialog
        {
            Title = "Extract card art",
            Filter = "PNG|*.png",
            FileName = DefaultPngExportFileName(_selected)
        };
        if (dlg.ShowDialog(this) != true)
            return;

        try
        {
            _modService.ExtractCardArt(GamePathBox.Text, _selected, dlg.FileName);
            Status("Extracted to " + dlg.FileName);
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message, "Floowan", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    private void Restore_Click(object sender, RoutedEventArgs e)
    {
        if (_modService is null || _selected is null || string.IsNullOrWhiteSpace(GamePathBox.Text))
            return;

        try
        {
            var ok = _modService.RestoreCardArt(GamePathBox.Text, _selected, _database);
            Status(ok ? "Restored from backup." : "No bundle backup found for this card.");
            if (ok)
            {
                _thumbnailCache.Invalidate(_selected);
                LoadCurrentPreview();
            }
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message, "Floowan", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    // --- Tools tab (backup browser) ---

    private void ToolsRefreshBackups_Click(object sender, RoutedEventArgs e) =>
        EnsureAndRefreshBackupBrowser();

    private void ToolsOpenBackupRoot_Click(object sender, RoutedEventArgs e)
    {
        try
        {
            EnsureBackupRootExists();
            OpenPathInExplorer(_backupRoot);
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message, "Floowan", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    private void ToolsOpenSelected_Click(object sender, RoutedEventArgs e) =>
        OpenSelectedBackupItem();

    private void ToolsBackupTree_MouseDoubleClick(object sender, MouseButtonEventArgs e) =>
        OpenSelectedBackupItem();

    private void EnsureAndRefreshBackupBrowser()
    {
        try
        {
            EnsureBackupRootExists();
            ToolsBackupPathBox.Text = _backupRoot;
            RefreshBackupTree();
        }
        catch (Exception ex)
        {
            ToolsBackupStatusText.Text = "Error: " + ex.Message;
            Status("Backup browser error: " + ex.Message);
        }
    }

    private void EnsureBackupRootExists()
    {
        Directory.CreateDirectory(_backupRoot);
    }

    private void RefreshBackupTree()
    {
        ToolsBackupTree.Items.Clear();

        if (!Directory.Exists(_backupRoot))
        {
            ToolsBackupStatusText.Text = "Backup folder does not exist.";
            return;
        }

        var dirs = 0;
        var files = 0;
        foreach (var entry in EnumerateBackupEntries(_backupRoot))
        {
            ToolsBackupTree.Items.Add(CreateBackupTreeItem(entry.path, entry.isDirectory));
            if (entry.isDirectory)
                dirs++;
            else
                files++;
        }

        ToolsBackupStatusText.Text = dirs + files == 0
            ? "Backup folder is empty."
            : $"Showing {dirs} folder(s), {files} file(s) at root.";
        Status("Backup browser refreshed.");
    }

    private static IEnumerable<(string path, bool isDirectory)> EnumerateBackupEntries(string directory)
    {
        IEnumerable<string> SafeEnumerate(Func<string, IEnumerable<string>> enumerator)
        {
            try
            {
                return enumerator(directory);
            }
            catch
            {
                return Array.Empty<string>();
            }
        }

        foreach (var dir in SafeEnumerate(Directory.EnumerateDirectories).OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase))
            yield return (dir, true);
        foreach (var file in SafeEnumerate(Directory.EnumerateFiles).OrderBy(Path.GetFileName, StringComparer.OrdinalIgnoreCase))
            yield return (file, false);
    }

    private TreeViewItem CreateBackupTreeItem(string path, bool isDirectory)
    {
        var item = new TreeViewItem
        {
            Header = Path.GetFileName(path),
            Tag = path,
            IsExpanded = false
        };

        if (isDirectory)
        {
            // Placeholder so the expand arrow appears; children load on expand.
            item.Items.Add(new TreeViewItem { Header = "…" });
            item.Expanded += BackupTreeItem_Expanded;
        }

        return item;
    }

    private void BackupTreeItem_Expanded(object sender, RoutedEventArgs e)
    {
        if (!ReferenceEquals(sender, e.OriginalSource))
            return;
        if (sender is not TreeViewItem item || item.Tag is not string path)
            return;

        item.Expanded -= BackupTreeItem_Expanded;
        item.Items.Clear();

        if (!Directory.Exists(path))
            return;

        foreach (var entry in EnumerateBackupEntries(path))
            item.Items.Add(CreateBackupTreeItem(entry.path, entry.isDirectory));
    }

    private void OpenSelectedBackupItem()
    {
        try
        {
            if (ToolsBackupTree.SelectedItem is not TreeViewItem item || item.Tag is not string path)
            {
                Status("Select a backup file or folder first.");
                return;
            }

            if (!File.Exists(path) && !Directory.Exists(path))
            {
                Status("Selected path no longer exists. Refresh and try again.");
                return;
            }

            OpenPathInExplorer(path);
        }
        catch (Exception ex)
        {
            MessageBox.Show(ex.Message, "Floowan", MessageBoxButton.OK, MessageBoxImage.Error);
        }
    }

    private static void OpenPathInExplorer(string path)
    {
        if (Directory.Exists(path))
        {
            Process.Start(new ProcessStartInfo
            {
                FileName = "explorer.exe",
                Arguments = path,
                UseShellExecute = true
            });
            return;
        }

        if (File.Exists(path))
        {
            Process.Start(new ProcessStartInfo
            {
                FileName = "explorer.exe",
                Arguments = "/select,\"" + path + "\"",
                UseShellExecute = true
            });
            return;
        }

        throw new FileNotFoundException("Path not found: " + path, path);
    }

    // --- Over-frame tab ---

    private void MainTabs_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        if (!IsLoaded)
            return;

        if (ToolsTab is not null && ReferenceEquals(MainTabs.SelectedItem, ToolsTab))
        {
            EnsureAndRefreshBackupBrowser();
            return;
        }

        if (OverFrameTab is null)
            return;
        if (!ReferenceEquals(MainTabs.SelectedItem, OverFrameTab))
            return;
        if (_ofInitialScanStarted || _ofGateReady)
            return;
        if (string.IsNullOrWhiteSpace(GamePathBox.Text) || _overFrameService is null)
            return;

        _ofInitialScanStarted = true;
        _ = EnsureOfGateAsync(showErrors: false);
    }

    private void OfSearchBox_KeyDown(object sender, KeyEventArgs e)
    {
        if (e.Key == Key.Enter)
        {
            _ofSearchDebounceTimer.Stop();
            RunOfSearch();
        }
    }

    private void OfSearchBox_TextChanged(object sender, TextChangedEventArgs e)
    {
        _ofSearchDebounceTimer.Stop();
        _ofSearchDebounceTimer.Start();
    }

    private void OnOfSearchDebounceTick(object? sender, EventArgs e)
    {
        _ofSearchDebounceTimer.Stop();
        ApplyDebouncedTextSearch(
            OfSearchBox.Text,
            RunOfSearch,
            () =>
            {
                OfCardList.ItemsSource = Array.Empty<CardRecord>();
                Status("Type at least 3 characters to search.");
            });
    }

    private void OfSearch_Click(object sender, RoutedEventArgs e)
    {
        _ofSearchDebounceTimer.Stop();
        RunOfSearch();
    }

    private void OfFilter_Changed(object sender, RoutedEventArgs e) => RunOfSearch();

    private void RunOfSearch()
    {
        if (_database is null)
        {
            Status("Open database.db first.");
            return;
        }

        var results = _database.SearchCards(
            OfSearchBox.Text,
            favoritesOnly: OfFavoritesOnlyBox.IsChecked == true,
            searchDescription: OfSearchDescBox.IsChecked == true,
            overframeOnly: OfOverframeOnlyBox.IsChecked == true,
            limit: 400);
        OfCardList.ItemsSource = results;
        BumpThumbnailLoadGeneration();
        Status($"Over-frame tab: {results.Count} card(s).");
    }

    private static void ApplyDebouncedTextSearch(string? text, Action runSearch, Action clearPartialQuery)
    {
        var trimmed = text?.Trim() ?? "";
        if (trimmed.Length == 0)
        {
            runSearch();
            return;
        }

        if (trimmed.Length < AutoSearchMinLength)
        {
            clearPartialQuery();
            return;
        }

        runSearch();
    }

    private void OfCardList_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        _ofSelected = OfCardList.SelectedItem as CardRecord;
        CleanupOfAutoGeneratedTemp();
        _ofReplacementImagePath = null;
        OfReplacementImage.Source = null;
        OfImagePathText.Text = "";
        _ofLiveTextureIsOverframe = false;
        ApplyOfPreviewLayout(hasReplacement: false);

        if (_ofSelected is null)
        {
            OfCardTitleText.Text = "(none selected)";
            OfCardMetaText.Text = "";
            OfGateEntryText.Text = "";
            OfCurrentArtImage.Source = null;
            OfDetailText.Text = "Target: 704?1024 RGBA32. Main art / frame overlap must use alpha ? 4 (not 0) or the frame goes black.";
            if (OfFrameStyleBox is not null)
                OfFrameStyleBox.SelectedIndex = -1;
            return;
        }

        OfCardTitleText.Text = _ofSelected.DisplayName;
        OfCardMetaText.Text =
            $"Bundle {_ofSelected.Bundle} ? id {_ofSelected.Id} ? overframe={_ofSelected.IsOverframe}" +
            (_ofSelected.OverframeBaseId is int baseId ? $" ? base={baseId}" : "");
        SuggestOfFrameStyle(_ofSelected);
        RefreshOfGateEntryStatus();
        LoadOfCurrentPreview();
    }

    private void SuggestOfFrameStyle(CardRecord card)
    {
        if (OfFrameStyleBox is null)
            return;

        var inferred = CardFrameTemplates.InferStyle(card.Name, card.Description);
        if (inferred is null)
        {
            OfFrameStyleBox.SelectedIndex = -1;
            return;
        }

        for (var i = 0; i < OfFrameStyleBox.Items.Count; i++)
        {
            if (OfFrameStyleBox.Items[i] is System.Windows.Controls.ComboBoxItem item
                && string.Equals(item.Tag as string, inferred.Value.ToString(), StringComparison.Ordinal))
            {
                OfFrameStyleBox.SelectedIndex = i;
                return;
            }
        }

        OfFrameStyleBox.SelectedIndex = -1;
    }

    /// <summary>Returns the Frame dropdown selection, or <c>null</c> when empty / unset.</summary>
    private CardFrameStyle? GetSelectedOfFrameStyle()
    {
        if (OfFrameStyleBox?.SelectedItem is System.Windows.Controls.ComboBoxItem item
            && item.Tag is string tag
            && Enum.TryParse<CardFrameStyle>(tag, out var selected))
        {
            return selected;
        }

        return null;
    }

    /// <summary>
    /// Requires an explicit Frame dropdown selection before OF actions that need a style.
    /// </summary>
    /// <returns><c>true</c> if the caller should abort.</returns>
    private bool WarnIfFrameStyleNotSelected()
    {
        if (GetSelectedOfFrameStyle() is not null)
            return false;

        MessageBox.Show(
            "Select a frame style before continuing.\n\n" +
            "The Frame dropdown is empty — choose Effect, Normal, Fusion, etc.",
            "Floowan — Frame required",
            MessageBoxButton.OK,
            MessageBoxImage.Warning);
        return true;
    }

    /// <summary>
    /// Blocks Over-frame mutating actions when the Frame dropdown is Link.
    /// Link punch/layout is unreliable — warn and abort rather than proceed.
    /// </summary>
    /// <returns><c>true</c> if the caller should abort.</returns>
    private bool WarnIfLinkFrameSelected()
    {
        if (GetSelectedOfFrameStyle() != CardFrameStyle.Link)
            return false;

        MessageBox.Show(
            "Link frames are not reliably supported for over-frame punch/layout.\n\n" +
            "This action has been cancelled. Choose a different frame style (for example Effect) if you still want to continue.",
            "Floowan — Link frame unsupported",
            MessageBoxButton.OK,
            MessageBoxImage.Warning);
        return true;
    }

    /// <summary>Empty-selection guard then Link guard. Returns true when the action should abort.</summary>
    private bool WarnIfFrameActionBlocked(bool requireSelection = true)
    {
        if (requireSelection && WarnIfFrameStyleNotSelected())
            return true;
        return WarnIfLinkFrameSelected();
    }

    private void RefreshOfGateEntryStatus()
    {
        if (_ofSelected is null || _overFrameService is null || string.IsNullOrWhiteSpace(GamePathBox.Text) || !_ofGateReady)
        {
            OfGateEntryText.Text = _ofGateReady ? "" : "Gate not located yet — open this tab or click Scan.";
            return;
        }

        try
        {
            var inGate = _overFrameService.IsInGate(GamePathBox.Text, _ofSelected, _database);
            if (inGate)
            {
                var artId = _ofSelected.ArtId
                            ?? _overFrameService.ResolveAndCacheArtId(GamePathBox.Text, _ofSelected, _database);
                OfGateEntryText.Text = $"Gate: present (art id {artId})";
            }
            else
            {
                OfGateEntryText.Text = "Gate: not registered";
            }
        }
        catch (Exception ex)
        {
            OfGateEntryText.Text = "Gate check failed: " + ex.Message;
        }
    }

    private void RefreshOfGateStatusFromCache()
    {
        var cached = _database?.GetOfCardAssetBundleId();
        if (!string.IsNullOrWhiteSpace(cached))
        {
            OfGateStatusText.Text = $"Gate bundle (cached): {cached}";
            _ofGateReady = true;
        }
        else
        {
            OfGateStatusText.Text = "Gate: not scanned yet";
            _ofGateReady = false;
        }
    }

    private async void OfScanGate_Click(object sender, RoutedEventArgs e) =>
        await EnsureOfGateAsync(showErrors: true);

    private async Task EnsureOfGateAsync(bool showErrors)
    {
        if (_overFrameService is null)
            return;
        if (string.IsNullOrWhiteSpace(GamePathBox.Text))
        {
            if (showErrors)
                MessageBox.Show("Set the Master Duel LocalData path first.", "Floowan");
            return;
        }

        SetUiBusy(true);
        OfGateStatusText.Text = "Scanning for of_card_asset…";
        Status("Scanning for of_card_asset…");
        var gamePath = GamePathBox.Text;
        var progress = new Progress<string>(msg =>
        {
            OfGateStatusText.Text = msg;
            Status(msg);
        });

        try
        {
            var result = await Task.Run(() =>
                _overFrameService.EnsureGateLocated(gamePath, _database, progress));
            if (result.Success)
            {
                _ofGateReady = true;
                OfGateStatusText.Text = result.Message + (result.BundleId is null ? "" : $" ({result.BundleId})");
                Status(result.Message);
                if (_database is not null)
                {
                    try
                    {
                        var marked = _overFrameService.SyncDatabaseFromGate(gamePath, _database, progress);
                        Status($"{result.Message} Synced {marked} over-frame flag(s).");
                        RunOfSearch();
                    }
                    catch (Exception syncEx)
                    {
                        Status(result.Message + " Sync skipped: " + syncEx.Message);
                    }
                }

                RefreshOfGateEntryStatus();
            }
            else
            {
                _ofGateReady = false;
                OfGateStatusText.Text = result.Message;
                Status(result.Message);
                if (showErrors)
                    MessageBox.Show(result.Message, "Floowan", MessageBoxButton.OK, MessageBoxImage.Warning);
            }
        }
        catch (Exception ex)
        {
            _ofGateReady = false;
            OfGateStatusText.Text = "Scan failed: " + ex.Message;
            Status(OfGateStatusText.Text);
            if (showErrors)
                MessageBox.Show(ex.Message, "Floowan", MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally
        {
            SetUiBusy(false);
        }
    }

    private void LoadOfCurrentPreview()
    {
        if (_ofSelected is null || _overFrameService is null || string.IsNullOrWhiteSpace(GamePathBox.Text))
            return;

        try
        {
            CleanupOfPreviewTemp();
            _ofPreviewTempPath = Path.Combine(Path.GetTempPath(), $"floowan-of-preview-{Guid.NewGuid():N}.png");
            // Always extract the live bundle texture as-is (full canvas). Do not art-hole-crop.
            _overFrameService.ExtractCardArt(GamePathBox.Text, _ofSelected, _ofPreviewTempPath);
            var info = _overFrameService.GetTextureInfo(GamePathBox.Text, _ofSelected);
            _ofLiveTextureIsOverframe = _ofSelected.IsOverframe
                || OverFrameAutoArtComposer.IsOverFrameTextureSize(info.Width, info.Height);

            // Already-OF textures use ??4 foil mask — flatten for on-screen visibility.
            // Normal 512?512 illusts load as-is.
            OfCurrentArtImage.Source = _ofLiveTextureIsOverframe
                ? LoadOfComposePreview(_ofPreviewTempPath)
                : LoadBitmap(_ofPreviewTempPath);
            ApplyOfPreviewLayout(hasReplacement: !string.IsNullOrWhiteSpace(_ofReplacementImagePath));

            OfDetailText.Text = _ofLiveTextureIsOverframe
                ? $"Live over-frame '{info.Name}' {info.Width}x{info.Height} format={info.Format}. Showing full {OverFrameConstants.Width}x{OverFrameConstants.Height} canvas (foil-mask flattened for preview)."
                : $"Texture '{info.Name}' {info.Width}x{info.Height} format={info.Format}. Normal art — Auto-create builds {OverFrameConstants.Width}x{OverFrameConstants.Height} RGBA32.";
        }
        catch (Exception ex)
        {
            OfCurrentArtImage.Source = null;
            _ofLiveTextureIsOverframe = false;
            OfDetailText.Text = "Preview failed: " + ex.Message;
        }
    }

    /// <summary>
    /// Normal cards: replacement replaces the pane. Already-OF cards: side-by-side
    /// live OF canvas + queued replacement so the full 704?1024 face stays visible.
    /// </summary>
    private void ApplyOfPreviewLayout(bool hasReplacement)
    {
        if (OfCurrentPreviewCol is null || OfReplacementPreviewCol is null)
            return;

        if (hasReplacement && _ofLiveTextureIsOverframe)
        {
            OfCurrentPreviewCol.Width = new GridLength(1, GridUnitType.Star);
            OfReplacementPreviewCol.Width = new GridLength(1, GridUnitType.Star);
            OfCurrentArtImage.Opacity = 1.0;
            OfReplacementImage.Opacity = 1.0;
        }
        else if (hasReplacement)
        {
            OfCurrentPreviewCol.Width = new GridLength(0);
            OfReplacementPreviewCol.Width = new GridLength(1, GridUnitType.Star);
            OfCurrentArtImage.Opacity = 0.0;
            OfReplacementImage.Opacity = 1.0;
        }
        else
        {
            OfCurrentPreviewCol.Width = new GridLength(1, GridUnitType.Star);
            OfReplacementPreviewCol.Width = new GridLength(0);
            OfCurrentArtImage.Opacity = 1.0;
            OfReplacementImage.Opacity = 0.0;
        }
    }

    private async void OfPreview_Click(object sender, RoutedEventArgs e)
    {
        // Prefer queued replacement / Auto-create result — show in the existing OF preview pane.
        if (!string.IsNullOrWhiteSpace(_ofReplacementImagePath) && File.Exists(_ofReplacementImagePath))
        {
            OfReplacementImage.Source = LoadOfComposePreview(_ofReplacementImagePath);
            ApplyOfPreviewLayout(hasReplacement: true);
            OfDetailText.Text =
                "Showing queued over-frame replacement in the preview pane. " +
                "This is a preview only - nothing was written to the game.";
            Status("Over-frame preview ready (not applied). Review, then Apply or Auto-create & apply.");
            return;
        }

        // Already-OF: show full live OF face in the pane (no re-compose required).
        if (_ofLiveTextureIsOverframe
            && !string.IsNullOrWhiteSpace(_ofPreviewTempPath)
            && File.Exists(_ofPreviewTempPath))
        {
            OfCurrentArtImage.Source = LoadOfComposePreview(_ofPreviewTempPath);
            ApplyOfPreviewLayout(hasReplacement: false);
            OfDetailText.Text =
                "Showing live over-frame canvas in the preview pane (foil-mask flattened).";
            Status("Over-frame preview ready (live OF).");
            return;
        }

        // Non-OF: compose what Auto-create would produce (rembg + frame -> 704x1024), without Apply.
        if (_overFrameService is null || _autoOverFrameArtService is null || _ofSelected is null)
        {
            MessageBox.Show("Select a card first.", "Floowan");
            return;
        }
        if (string.IsNullOrWhiteSpace(GamePathBox.Text))
        {
            MessageBox.Show("Set the Master Duel LocalData path first.", "Floowan");
            return;
        }
        if (WarnIfFrameActionBlocked())
            return;

        SetUiBusy(true);
        var card = _ofSelected;
        var progress = new Progress<string>(Status);
        try
        {
            var sourceLabel = await ComposeAutoOverFrameReplacementAsync(card, progress);
            OfDetailText.Text =
                $"Preview composited with {GetSelectedOfFrameStyle()} from {sourceLabel}: " +
                "foil-mask art (a/4), overflow cut at lore box with opaque panel underlay. " +
                "This is a preview only - nothing was written to the game.";
            Status("Over-frame preview ready (not applied). Review, then Apply or Auto-create & apply.");
            // ComposeAutoOverFrameReplacementAsync already updated OfReplacementImage + layout.
        }
        catch (Exception ex)
        {
            CleanupOfAutoGeneratedTemp();
            _ofReplacementImagePath = null;
            Status("Over-frame preview failed: " + ex.Message);
            MessageBox.Show(
                "Could not compose over-frame preview:\n\n" + ex.Message,
                "Floowan",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
        finally
        {
            SetUiBusy(false);
        }
    }

    /// <summary>
    /// Resolve clean source art, run rembg + frame compose to a temp 704x1024 PNG,
    /// and queue it as the OF replacement preview. Does not apply to the game.
    /// </summary>
    private async Task<string> ComposeAutoOverFrameReplacementAsync(
        CardRecord card,
        IProgress<string>? progress)
    {
        if (_overFrameService is null || _autoOverFrameArtService is null)
            throw new InvalidOperationException("Over-frame services are not initialized.");
        if (string.IsNullOrWhiteSpace(GamePathBox.Text))
            throw new InvalidOperationException("Master Duel LocalData path is not set.");

        string? autoSourcePath = null;
        try
        {
            autoSourcePath = Path.Combine(
                Path.GetTempPath(),
                $"floowan-of-source-{Guid.NewGuid():N}.png");
            var sourceLabel = _overFrameService.ResolveAutoCreateSourceArt(
                GamePathBox.Text, card, autoSourcePath);
            progress?.Report($"Auto-create source: {sourceLabel}");

            CleanupOfAutoGeneratedTemp();
            _ofAutoGeneratedTempPath = Path.Combine(
                Path.GetTempPath(),
                $"floowan-of-auto-{Guid.NewGuid():N}.png");
            var frameStyle = GetSelectedOfFrameStyle()
                ?? throw new InvalidOperationException("Frame style is required.");
            await _autoOverFrameArtService.CreateAsync(
                autoSourcePath,
                _ofAutoGeneratedTempPath,
                frameStyle,
                progress);

            _ofReplacementImagePath = _ofAutoGeneratedTempPath;
            OfImagePathText.Text =
                "Auto-generated 704x1024 replacement (review before Apply): " +
                _ofAutoGeneratedTempPath;
            OfReplacementImage.Source = LoadOfComposePreview(_ofAutoGeneratedTempPath);
            ApplyOfPreviewLayout(hasReplacement: true);
            return sourceLabel;
        }
        finally
        {
            if (autoSourcePath is not null && File.Exists(autoSourcePath))
            {
                try { File.Delete(autoSourcePath); } catch { /* ignore */ }
            }
        }
    }

    private void OfSelectImage_Click(object sender, RoutedEventArgs e)
    {
        var dlg = new OpenFileDialog
        {
            Title = "Select 704?1024 over-frame art",
            Filter = "Images|*.png;*.jpg;*.jpeg;*.bmp;*.webp|All files|*.*"
        };
        if (dlg.ShowDialog(this) != true)
            return;

        _ofReplacementImagePath = dlg.FileName;
        OfImagePathText.Text = "Replacement (prefer 704?1024): " + dlg.FileName;
        OfReplacementImage.Source = LoadOfComposePreview(dlg.FileName);
        ApplyOfPreviewLayout(hasReplacement: true);
    }

    private async void OfAutoCreate_Click(object sender, RoutedEventArgs e)
    {
        if (_overFrameService is null || _autoOverFrameArtService is null || _ofSelected is null)
        {
            MessageBox.Show("Select a card first.", "Floowan");
            return;
        }
        if (string.IsNullOrWhiteSpace(GamePathBox.Text))
        {
            MessageBox.Show("Set the Master Duel LocalData path first.", "Floowan");
            return;
        }
        if (WarnIfFrameActionBlocked())
            return;

        SetUiBusy(true);
        var card = _ofSelected;
        var progress = new Progress<string>(Status);
        try
        {
            var sourceLabel = await ComposeAutoOverFrameReplacementAsync(card, progress);
            var frameStyle = GetSelectedOfFrameStyle();
            OfDetailText.Text =
                $"Composited with {frameStyle} from {sourceLabel}: foil-mask art (a/4), overflow cut at lore box with opaque panel underlay. Confirm Gate says present after Apply, then fully restart Master Duel.";
            Status("Automatic over-frame art is ready. Review the preview, then click Apply over-frame (or use Auto-create & apply).");
        }
        catch (Exception ex)
        {
            CleanupOfAutoGeneratedTemp();
            _ofReplacementImagePath = null;
            Status("Automatic over-frame failed: " + ex.Message);
            MessageBox.Show(
                "Could not automatically create over-frame art:\n\n" + ex.Message,
                "Floowan",
                MessageBoxButton.OK,
                MessageBoxImage.Error);
        }
        finally
        {
            SetUiBusy(false);
        }
    }

    private async void OfAutoCreateAndApply_Click(object sender, RoutedEventArgs e)
    {
        if (_overFrameService is null || _autoOverFrameArtService is null || _ofSelected is null)
        {
            MessageBox.Show("Select a card first.", "Floowan");
            return;
        }
        if (string.IsNullOrWhiteSpace(GamePathBox.Text))
        {
            MessageBox.Show("Set the Master Duel LocalData path first.", "Floowan");
            return;
        }
        if (WarnIfFrameActionBlocked())
            return;

        if (!_ofGateReady)
            await EnsureOfGateAsync(showErrors: true);
        if (!_ofGateReady)
            return;

        SetUiBusy(true);
        var card = _ofSelected;
        var gamePath = GamePathBox.Text;
        var progress = new Progress<string>(Status);
        try
        {
            await ComposeAutoOverFrameReplacementAsync(card, progress);
            OfImagePathText.Text = "Auto-generated 704x1024 replacement: " + _ofAutoGeneratedTempPath;

            Status("Applying over-frame (texture + gate)...");
            var result = await Task.Run(() =>
                _overFrameService.ApplyOverFrame(gamePath, card, _ofAutoGeneratedTempPath!, createBackup: true, _database));
            Status(result.Message);
            MessageBox.Show(result.Message, "Floowan",
                MessageBoxButton.OK,
                result.Success ? MessageBoxImage.Information : MessageBoxImage.Error);
            if (result.Success)
            {
                _ofReplacementImagePath = null;
                OfReplacementImage.Source = null;
                ApplyOfPreviewLayout(hasReplacement: false);
                _thumbnailCache.Invalidate(card);
                RunOfSearch();
                ReselectOfCard(card.Id);
            }
        }
        catch (Exception ex)
        {
            Status("Auto-create & apply failed: " + ex.Message);
            MessageBox.Show(ex.Message, "Floowan", MessageBoxButton.OK, MessageBoxImage.Error);
        }
        finally
        {
            SetUiBusy(false);
        }
    }

    private async void OfApply_Click(object sender, RoutedEventArgs e)
    {
        if (_overFrameService is null || _ofSelected is null)
        {
            MessageBox.Show("Select a card first.", "Floowan");
            return;
        }
        if (string.IsNullOrWhiteSpace(GamePathBox.Text))
        {
            MessageBox.Show("Set the Master Duel LocalData path first.", "Floowan");
            return;
        }
        if (string.IsNullOrWhiteSpace(_ofReplacementImagePath))
        {
            MessageBox.Show("Select a 704?1024 replacement image first.", "Floowan");
            return;
        }
        if (WarnIfFrameActionBlocked())
            return;

        if (!_ofGateReady)
            await EnsureOfGateAsync(showErrors: true);
        if (!_ofGateReady)
            return;

                var gamePath = GamePathBox.Text;
        var card = _ofSelected;
        var image = _ofReplacementImagePath;
        SetUiBusy(true);
        Status("Applying over-frame…");
        try
        {
            var result = await Task.Run(() =>
                _overFrameService.ApplyOverFrame(gamePath, card, image, createBackup: true, _database));
            Status(result.Message);
            MessageBox.Show(result.Message, "Floowan",
                MessageBoxButton.OK,
                result.Success ? MessageBoxImage.Information : MessageBoxImage.Error);
            if (result.Success)
            {
                _ofReplacementImagePath = null;
                OfReplacementImage.Source = null;
                ApplyOfPreviewLayout(hasReplacement: false);
                _thumbnailCache.Invalidate(card);
                RunOfSearch();
                ReselectOfCard(card.Id);
            }
        }
        finally
        {
            SetUiBusy(false);
        }
    }

    private async void OfEnableGate_Click(object sender, RoutedEventArgs e)
    {
        if (_overFrameService is null || _ofSelected is null)
        {
            MessageBox.Show("Select a card first.", "Floowan");
            return;
        }
        if (string.IsNullOrWhiteSpace(GamePathBox.Text))
        {
            MessageBox.Show("Set the Master Duel LocalData path first.", "Floowan");
            return;
        }
        if (WarnIfFrameActionBlocked(requireSelection: false))
            return;

        if (!_ofGateReady)
            await EnsureOfGateAsync(showErrors: true);
        if (!_ofGateReady)
            return;

                var gamePath = GamePathBox.Text;
        var card = _ofSelected;
        SetUiBusy(true);
        Status("Updating of_card_asset gate…");
        try
        {
            var result = await Task.Run(() =>
                _overFrameService.EnableGateOnly(gamePath, card, createBackup: true, _database));
            Status(result.Message);
            MessageBox.Show(result.Message, "Floowan",
                MessageBoxButton.OK,
                result.Success ? MessageBoxImage.Information : MessageBoxImage.Error);
            if (result.Success)
            {
                RunOfSearch();
                ReselectOfCard(card.Id);
            }
        }
        finally
        {
            SetUiBusy(false);
        }
    }

    private async void OfRemove_Click(object sender, RoutedEventArgs e)
    {
        if (_overFrameService is null || _ofSelected is null)
        {
            MessageBox.Show("Select a card first.", "Floowan");
            return;
        }
        if (string.IsNullOrWhiteSpace(GamePathBox.Text))
        {
            MessageBox.Show("Set the Master Duel LocalData path first.", "Floowan");
            return;
        }
        if (WarnIfFrameActionBlocked(requireSelection: false))
            return;

        if (!_ofGateReady)
            await EnsureOfGateAsync(showErrors: true);
        if (!_ofGateReady)
            return;

                var gamePath = GamePathBox.Text;
        var card = _ofSelected;
        SetUiBusy(true);
        Status("Removing from of_card_asset…");
        try
        {
            var result = await Task.Run(() =>
                _overFrameService.RemoveFromGate(gamePath, card, createBackup: true, _database));
            Status(result.Message);
            MessageBox.Show(result.Message, "Floowan",
                MessageBoxButton.OK,
                result.Success ? MessageBoxImage.Information : MessageBoxImage.Error);
            if (result.Success)
            {
                RunOfSearch();
                ReselectOfCard(card.Id);
            }
        }
        finally
        {
            SetUiBusy(false);
        }
    }

    private async void OfRestore_Click(object sender, RoutedEventArgs e)
    {
        if (_overFrameService is null || _ofSelected is null || string.IsNullOrWhiteSpace(GamePathBox.Text))
            return;
        if (WarnIfFrameActionBlocked(requireSelection: false))
            return;

        if (!_ofGateReady)
            await EnsureOfGateAsync(showErrors: true);

        var gamePath = GamePathBox.Text;
        var card = _ofSelected;
        SetUiBusy(true);
        Status("Restoring over-frame backups…");
        try
        {
            var result = await Task.Run(() =>
                _overFrameService.RestoreBackups(gamePath, card, _database));
            Status(result.Message);
            MessageBox.Show(result.Message, "Floowan",
                MessageBoxButton.OK,
                result.Success ? MessageBoxImage.Information : MessageBoxImage.Warning);
            if (result.Success)
            {
                _thumbnailCache.Invalidate(card);
                RunOfSearch();
                ReselectOfCard(card.Id);
            }
        }
        finally
        {
            SetUiBusy(false);
        }
    }

    private void ReselectOfCard(int cardId)
    {
        if (OfCardList.ItemsSource is IEnumerable<CardRecord> items)
        {
            var match = items.FirstOrDefault(c => c.Id == cardId);
            if (match is not null)
            {
                OfCardList.SelectedItem = match;
                return;
            }
        }

        _ofSelected = _database?.GetById(cardId);
        if (_ofSelected is not null)
        {
            OfCardTitleText.Text = _ofSelected.DisplayName;
            OfCardMetaText.Text =
                $"Bundle {_ofSelected.Bundle} ? id {_ofSelected.Id} ? overframe={_ofSelected.IsOverframe}";
            RefreshOfGateEntryStatus();
            LoadOfCurrentPreview();
        }
    }

    private static BitmapImage LoadBitmap(string path)
    {
        var bmp = new BitmapImage();
        bmp.BeginInit();
        bmp.CacheOption = BitmapCacheOption.OnLoad;
        bmp.UriSource = new Uri(path);
        bmp.EndInit();
        bmp.Freeze();
        return bmp;
    }

    /// <summary>
    /// OF textures use ??4 foil mask which WPF treats as nearly invisible. Flatten
    /// those pixels for preview only so art + lore box are visible on screen.
    /// </summary>
    private static BitmapImage LoadOfComposePreview(string path)
    {
        using var image = SixLabors.ImageSharp.Image.Load<SixLabors.ImageSharp.PixelFormats.Rgba32>(path);
        using var flat = OverFrameAutoArtComposer.FlattenFoilMaskForPreview(image);
        using var ms = new MemoryStream();
        flat.Save(ms, new SixLabors.ImageSharp.Formats.Png.PngEncoder());
        ms.Position = 0;

        var bmp = new BitmapImage();
        bmp.BeginInit();
        bmp.CacheOption = BitmapCacheOption.OnLoad;
        bmp.StreamSource = ms;
        bmp.EndInit();
        bmp.Freeze();
        return bmp;
    }

    private void CleanupPreviewTemp()
    {
        if (_previewTempPath is not null && File.Exists(_previewTempPath))
        {
            try { File.Delete(_previewTempPath); } catch { /* ignore */ }
        }
        _previewTempPath = null;
    }

    private void CleanupOfPreviewTemp()
    {
        if (_ofPreviewTempPath is not null && File.Exists(_ofPreviewTempPath))
        {
            try { File.Delete(_ofPreviewTempPath); } catch { /* ignore */ }
        }
        _ofPreviewTempPath = null;
    }

    private void CleanupOfAutoGeneratedTemp()
    {
        if (_ofAutoGeneratedTempPath is not null && File.Exists(_ofAutoGeneratedTempPath))
        {
            try { File.Delete(_ofAutoGeneratedTempPath); } catch { /* ignore */ }
        }
        _ofAutoGeneratedTempPath = null;
    }

    private void Cleanup()
    {
        BumpThumbnailLoadGeneration();
        _cardSearchDebounceTimer.Stop();
        _ofSearchDebounceTimer.Stop();
        CleanupPreviewTemp();
        CleanupOfPreviewTemp();
        CleanupOfAutoGeneratedTemp();
        _thumbnailCache.Dispose();
        _modService?.Dispose();
        _overFrameService?.Dispose();
        _autoOverFrameArtService?.Dispose();
        _database?.Dispose();
    }

    private void Status(string text) => StatusText.Text = text;

    private void DbFilter_KeyDown(object sender, KeyEventArgs e)
    {
        if (e.Key == Key.Enter)
            RunDatabaseQuery(resetOffset: true);
    }

    private void DbApplyFilters_Click(object sender, RoutedEventArgs e) =>
        RunDatabaseQuery(resetOffset: true);

    private void DbClearFilters_Click(object sender, RoutedEventArgs e)
    {
        DbFilterIdBox.Text = "";
        DbFilterNameBox.Text = "";
        DbFilterDescBox.Text = "";
        DbFilterFavoriteBox.SelectedIndex = 0;
        DbFilterBackupBox.SelectedIndex = 0;
        DbFilterModdedNameBox.SelectedIndex = 0;
        DbFilterModdedDescBox.SelectedIndex = 0;
        RunDatabaseQuery(resetOffset: true);
    }

    private void DbPrevPage_Click(object sender, RoutedEventArgs e)
    {
        _dbOffset = Math.Max(0, _dbOffset - DbPageSize);
        RunDatabaseQuery(resetOffset: false);
    }

    private void DbNextPage_Click(object sender, RoutedEventArgs e)
    {
        if (_dbOffset + DbPageSize < _dbTotalMatching)
            _dbOffset += DbPageSize;
        RunDatabaseQuery(resetOffset: false);
    }

    private void RunDatabaseQuery(bool resetOffset)
    {
        if (_database is null)
        {
            Status("Open database.db first.");
            return;
        }

        if (resetOffset)
            _dbOffset = 0;

        try
        {
            var filters = BuildDatabaseFilters();
            _dbTotalMatching = _database.CountCards(filters);
            var page = _database.QueryCards(filters);

            var keepId = _dbSelected?.Id;
            DbCardGrid.ItemsSource = page;

            if (keepId is int id)
            {
                var match = page.FirstOrDefault(c => c.Id == id);
                if (match is not null)
                    DbCardGrid.SelectedItem = match;
                else
                    ClearDatabaseEditForm();
            }
            else if (_dbSelected is null)
            {
                ClearDatabaseEditForm();
            }

            var pageStart = _dbTotalMatching == 0 ? 0 : _dbOffset + 1;
            var pageEnd = Math.Min(_dbOffset + page.Count, _dbTotalMatching);
            DbPageInfoText.Text = $"Showing {pageStart}–{pageEnd} of {_dbTotalMatching}";
            DbPrevPageButton.IsEnabled = _dbOffset > 0;
            DbNextPageButton.IsEnabled = _dbOffset + DbPageSize < _dbTotalMatching;
            Status($"Database: {page.Count} row(s) on page ({_dbTotalMatching} match filter).");
        }
        catch (Exception ex)
        {
            Status("Database query error: " + ex.Message);
        }
    }

    private CardQueryFilters BuildDatabaseFilters()
    {
        int? cardId = null;
        var idText = DbFilterIdBox.Text?.Trim() ?? "";
        if (idText.Length > 0)
        {
            if (!int.TryParse(idText, out var parsed) || parsed <= 0)
                throw new InvalidOperationException("Card ID filter must be a positive integer.");
            cardId = parsed;
        }

        return new CardQueryFilters
        {
            CardId = cardId,
            NameContains = NullIfBlank(DbFilterNameBox.Text),
            DescriptionContains = NullIfBlank(DbFilterDescBox.Text),
            Favorite = TriStateBool(DbFilterFavoriteBox.SelectedIndex),
            HasBackup = TriStateBool(DbFilterBackupBox.SelectedIndex),
            HasModdedName = TriStateBool(DbFilterModdedNameBox.SelectedIndex),
            HasModdedDescription = TriStateBool(DbFilterModdedDescBox.SelectedIndex),
            Limit = DbPageSize,
            Offset = _dbOffset
        };
    }

    private static string DefaultPngExportFileName(CardRecord? card)
    {
        if (card is null)
            return "card.png";

        var slug = ImagePreparation.Slugify(card.DisplayName);
        if (string.IsNullOrWhiteSpace(slug))
            slug = ImagePreparation.Slugify(card.Name);
        if (string.IsNullOrWhiteSpace(slug))
            slug = ImagePreparation.Slugify(card.Bundle);
        if (string.IsNullOrWhiteSpace(slug))
            slug = "card";

        return slug + ".png";
    }

    private static string? NullIfBlank(string? value)
    {
        var trimmed = value?.Trim() ?? "";
        return trimmed.Length == 0 ? null : trimmed;
    }

    private static bool? TriStateBool(int selectedIndex) => selectedIndex switch
    {
        1 => true,
        2 => false,
        _ => null
    };

    private void DbCardGrid_SelectionChanged(object sender, SelectionChangedEventArgs e)
    {
        _dbSelected = DbCardGrid.SelectedItem as CardRecord;
        if (_dbSelected is null)
        {
            ClearDatabaseEditForm();
            return;
        }

        LoadDatabaseEditForm(_dbSelected);
    }

    private void LoadDatabaseEditForm(CardRecord card)
    {
        DbEditIdBox.Text = card.Id.ToString();
        DbEditNameBox.Text = card.Name;
        DbEditDescBox.Text = card.Description;
        DbEditModdedNameBox.Text = card.ModdedName ?? "";
        DbEditModdedDescBox.Text = card.ModdedDescription ?? "";
        DbEditBundleBox.Text = card.Bundle;
        DbEditDataIndexBox.Text = card.DataIndex.ToString();
        DbEditFavoriteBox.IsChecked = card.Favorite;
        DbEditHasBackupBox.Text = card.HasBackup ? "True" : "False";
    }

    private void ClearDatabaseEditForm()
    {
        _dbSelected = null;
        DbEditIdBox.Text = "";
        DbEditNameBox.Text = "";
        DbEditDescBox.Text = "";
        DbEditModdedNameBox.Text = "";
        DbEditModdedDescBox.Text = "";
        DbEditBundleBox.Text = "";
        DbEditDataIndexBox.Text = "";
        DbEditFavoriteBox.IsChecked = false;
        DbEditHasBackupBox.Text = "";
    }

    private void DbDiscard_Click(object sender, RoutedEventArgs e)
    {
        if (_dbSelected is null)
        {
            ClearDatabaseEditForm();
            return;
        }

        LoadDatabaseEditForm(_dbSelected);
        Status("Discarded Database edit changes.");
    }

    private void DbSave_Click(object sender, RoutedEventArgs e)
    {
        if (_database is null)
        {
            Status("Open database.db first.");
            return;
        }

        if (_dbSelected is null || !int.TryParse(DbEditIdBox.Text, out var id))
        {
            Status("Select a Database row to edit.");
            return;
        }

        try
        {
            _database.UpdateCard(
                id,
                DbEditNameBox.Text ?? "",
                DbEditDescBox.Text ?? "",
                NullIfBlank(DbEditModdedNameBox.Text),
                NullIfBlank(DbEditModdedDescBox.Text),
                DbEditFavoriteBox.IsChecked == true);

            RunDatabaseQuery(resetOffset: false);
            Status($"Saved card id {id}.");
        }
        catch (Exception ex)
        {
            Status("Database save error: " + ex.Message);
        }
    }
}
